### ISSUE TITLE
feat: Data Seed Function

### ISSUE THREAD

**Issue by demirbasaf** [TurkeyLearningInitiative/api#12]
# Task Description

A function should be written to seed university, major and course data to given database.

# Acceptance Criteria

- [ ] All universities are created in the database.
- [ ] All majors are created in the database.
- [ ] All courses are created with their related majors in the database.
