### ISSUE TITLE
feat: Filter & Search Endpoint

### ISSUE THREAD

**Issue by demirbasaf** [TurkeyLearningInitiative/api#13]
# Task Description

An endpoint should be developed to filter and search lecture notes by their university, major, course and tags info

# Acceptance Criteria

- [ ] Lecture notes can be filtered by their meta data
- [ ] Lecture notes can be searched by their meta data
- [ ] If no lecture notes found for given filters or searchText, it should return an empty array
